# -*- coding: utf-8 -*-
"""Publication_Grade_EEG_ME_vs_MI_Reanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXQS9Y83Avddj1pPt7Fm7JBlmKGqUMzF

# Publication-grade reanalysis: motor execution versus motor imagery

**Dataset:** PhysioNet EEG Motor Movement/Imagery Database (EEGMMIDB), version 1.0.0  
**Primary question:** Can event-related scalp EEG distinguish motor execution (ME) from motor imagery (MI) in participants who were not used to train or tune the model?

This notebook is a clean reanalysis companion to the original exploratory Colab. It does not overwrite the original workflow or its reported numbers. Its purpose is to produce results that can support a defensible paper after the notebook has been run on all eligible participants.

The design deliberately treats **participant generalization** as the estimand. Every epoch from a participant remains in the same outer fold. Scaling, supervised feature selection, spatial-filter estimation, and hyperparameter selection are fitted only with training participants.

> Do not copy numbers into the manuscript until the full run, quality-control report, confidence intervals, and permutation test have completed successfully.

## Why the original scores need to be rerun

| Original operation | Consequence | Correction here |
|---|---|---|
| One 60- or 120-second vector per run | Rest and task intervals are mixed; transient ERD/ERS patterns are diluted | Use annotation-locked T1/T2 trials with a pre-cue rest reference |
| The 7–30 Hz filter is used only in a sample-inspection cell | Bulk feature loops operate on newly loaded, apparently unfiltered recordings | Apply one declared filter inside the reusable loading function |
| Raw Mel power is flattened with library defaults | Frequency limits and spectral resolution are not EEG-prespecified; no log conversion is applied | Use explicit mu/beta ERD features and report every transform parameter |
| Random row-level train/test split | Runs from the same participant can enter both sets | Hold out entire participants in every outer fold |
| Scaling before the split | Test-set distribution influences the model | Put scaling inside the model pipeline |
| ANOVA selection on all observations | Test labels leak into feature selection | Fit `SelectKBest` inside each inner/outer training fold |
| Ascending F-value sort | The retained set contains the weakest, not strongest, F-statistics among candidates | Let `SelectKBest` rank F-statistics correctly inside folds |
| The 60-s selector uses rest/ME/MI, then rest is removed | The selection target differs from the final binary model | Select features using the same ME-versus-MI target fitted by the classifier |
| ROC–AUC from class predictions | AUC is reduced to a single threshold-dependent result | Compute AUC from probabilities or decision scores |
| Broad left/right channel averaging | Sensorimotor lateralization is removed | Preserve individual FC/C/CP electrodes and compare an ERD baseline with CSP–LDA |
| No documented artifact rule in the bulk loop | ME may be separated from MI using muscle/electrode-motion contamination | Apply a declared peak-to-peak rule, report differential rejection, and perform sensitivity analysis |

The notebook also logs failed or incomplete participants instead of silently inferring exclusions from `NaN` feature rows.

## Protocol, estimand, and prespecified outcomes

Execution and imagery are defined by **run number**, not by T0/T1/T2. In task runs, T0 is rest and T1/T2 identify the cued body movement.

- ME: runs 3, 5, 7, 9, 11, and 13
- MI: runs 4, 6, 8, 10, 12, and 14
- Unilateral runs: T1 = left fist; T2 = right fist
- Bilateral runs: T1 = both fists; T2 = both feet

**Primary endpoint:** participant-mean balanced accuracy under nested participant-disjoint cross-validation.  
**Secondary endpoints:** participant-mean ROC–AUC, macro-F1, sensitivity, specificity, and average precision.  
**Primary model:** baseline-referenced mu/beta ERD features with fold-local selection and logistic regression.  
**EEG-specific comparator:** CSP with shrinkage LDA.  
**Negative control:** prior-probability dummy classifier.

The first-60-seconds comparison is retained only as a **duration sensitivity analysis**. It compares the trials whose cue onset occurs in the first 60 seconds with all available trials; it is not described as a 60-second EEG epoch.
"""

# Colab/runtime setup. Re-run this cell if the runtime restarts.
import sys
import subprocess
import gc

packages = [
    "mne>=1.7,<2.0",
    "numpy>=1.24,<3.0",
    "pandas>=2.0,<3.0",
    "scipy>=1.10,<2.0",
    "scikit-learn>=1.4,<2.0",
    "matplotlib>=3.7,<4.0",
    "seaborn>=0.13,<1.0",
    "pyriemann>=0.7,<1.0",
]
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

from __future__ import annotations

import hashlib
import json
import os
import platform
import random
import shutil
import sys
import warnings
from dataclasses import asdict, dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import mne
import numpy as np
import pandas as pd
import pyriemann
import scipy
import seaborn as sns
import sklearn
from IPython.display import display
from mne.datasets import eegbci
from mne.decoding import CSP
from mne.io import read_raw_edf
from mne.time_frequency import psd_array_welch
from pyriemann.estimation import Covariances
from pyriemann.tangentspace import TangentSpace
from scipy.stats import wilcoxon
from sklearn.base import clone
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.dummy import DummyClassifier
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
)
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("default")
sns.set_theme(style="whitegrid", context="notebook")

print({
    "python": platform.python_version(),
    "mne": mne.__version__,
    "numpy": np.__version__,
    "pandas": pd.__version__,
    "scipy": scipy.__version__,
    "scikit_learn": sklearn.__version__,
    "pyriemann": pyriemann.__version__,
})

@dataclass(frozen=True)
class AnalysisConfig:
    seed: int = 2026
    subjects: tuple[int, ...] = tuple(range(1, 110))
    task_runs: tuple[int, ...] = tuple(range(3, 15))
    l_freq: float = 8.0
    h_freq: float = 30.0
    epoch_tmin: float = -2.0
    epoch_tmax: float = 3.5
    baseline_tmin: float = -2.0
    baseline_tmax: float = -0.5
    task_tmin: float = 0.5
    task_tmax: float = 3.5
    target_sfreq: float = 80.0
    reject_peak_to_peak_uv: float = 200.0
    outer_folds: int = 5
    inner_folds: int = 4
    n_bootstrap: int = 2000
    n_permutations: int = 1000
    n_jobs: int = 1  # CSP is memory-intensive; increase only after checking RAM.
    run_csp: bool = True
    run_riemann: bool = True
    run_duration_sensitivity: bool = True
    run_permutation_test: bool = False  # Turn on for the final paper run.


CFG = AnalysisConfig()
random.seed(CFG.seed)
np.random.seed(CFG.seed)

IN_COLAB = "google.colab" in sys.modules
WORK_DIR = Path("/content/eegmmidb_me_mi_reanalysis" if IN_COLAB else "./eegmmidb_me_mi_reanalysis")
DATA_DIR = WORK_DIR / "physionet_data"
CACHE_DIR = WORK_DIR / "cache"
OUTPUT_DIR = WORK_DIR / "paper_outputs"
for directory in (DATA_DIR, CACHE_DIR, OUTPUT_DIR):
    directory.mkdir(parents=True, exist_ok=True)

CONFIG_PATH = OUTPUT_DIR / "analysis_config.json"

CONFIG_PATH.write_text(json.dumps(asdict(CFG), indent=2))
print(f"Working directory: {WORK_DIR.resolve()}")
print(f"Full analysis: {len(CFG.subjects)} requested participants, runs {CFG.task_runs}")

RUN_INFO = {
    3:  ("execution", "unilateral", 1),
    4:  ("imagery",   "unilateral", 1),
    5:  ("execution", "bilateral",  1),
    6:  ("imagery",   "bilateral",  1),
    7:  ("execution", "unilateral", 2),
    8:  ("imagery",   "unilateral", 2),
    9:  ("execution", "bilateral",  2),
    10: ("imagery",   "bilateral",  2),
    11: ("execution", "unilateral", 3),
    12: ("imagery",   "unilateral", 3),
    13: ("execution", "bilateral",  3),
    14: ("imagery",   "bilateral",  3),
}

SENSORIMOTOR_CHANNELS = [
    "FC5", "FC3", "FC1", "FCz", "FC2", "FC4", "FC6",
    "C5",  "C3",  "C1",  "Cz",  "C2",  "C4",  "C6",
    "CP5", "CP3", "CP1", "CPz", "CP2", "CP4", "CP6",
]

preproc_identity = {
    "subjects": CFG.subjects,
    "runs": CFG.task_runs,
    "bandpass": [CFG.l_freq, CFG.h_freq],
    "epoch": [CFG.epoch_tmin, CFG.epoch_tmax],
    "rejection_uv": CFG.reject_peak_to_peak_uv,
    "channels": SENSORIMOTOR_CHANNELS,
}
PREPROC_TAG = hashlib.sha1(
    json.dumps(preproc_identity, sort_keys=True, default=list).encode("utf-8")
).hexdigest()[:10]
EPOCH_CACHE = CACHE_DIR / f"me_mi_sensorimotor_{PREPROC_TAG}-epo.fif"
LOAD_LOG_CACHE = CACHE_DIR / f"loading_qc_{PREPROC_TAG}.csv"

protocol = pd.DataFrame(
    [
        {
            "run": run,
            "condition": condition,
            "task_family": family,
            "repetition": repetition,
            "T1": "left fist" if family == "unilateral" else "both fists",
            "T2": "right fist" if family == "unilateral" else "both feet",
        }
        for run, (condition, family, repetition) in RUN_INFO.items()
    ]
)
display(protocol)
assert set(protocol.run) == set(CFG.task_runs)
assert (protocol.condition.value_counts() == 6).all()

"""## Signal preparation and event extraction

The pipeline standardizes EEGBCI channel names, assigns a standard montage, computes an average reference using all available EEG channels, band-pass filters 8–30 Hz, and then retains 21 FC/C/CP electrodes without left–right averaging. Because the upper cutoff is 30 Hz, a separate line-noise notch is unnecessary for the classification signal. T1/T2 epochs span −2.0 to 3.5 s around cue onset; features use −2.0 to −0.5 s as the rest reference and 0.5 to 3.5 s as the task interval.

A fixed 200 µV peak-to-peak threshold is applied identically to ME and MI. The rejection rate is reported by condition because disproportionately rejecting execution trials could itself bias the analysis. For a final sensitivity analysis, repeat the full evaluation with no rejection and with a prespecified alternative threshold (for example, 150 µV); do not choose the threshold by whichever result is more favourable.

EEGMMIDB does not include dedicated EOG/EMG channels. Therefore, even after amplitude rejection, a remaining ME–MI difference cannot automatically be described as purely cortical. The paper should acknowledge this limitation and inspect scalp/spectral patterns.

"""

def movement_name(task_family: str, event_name: str) -> str:
    mapping = {
        ("unilateral", "T1"): "left_fist",
        ("unilateral", "T2"): "right_fist",
        ("bilateral", "T1"): "both_fists",
        ("bilateral", "T2"): "both_feet",
    }
    return mapping[(task_family, event_name)]


def load_run(subject: int, run: int):
    condition, task_family, repetition = RUN_INFO[run]
    files = eegbci.load_data(
        subject,
        runs=[run],
        path=str(DATA_DIR),
        update_path=False,
    )
    if len(files) != 1:
        raise RuntimeError(f"Expected one EDF for subject {subject}, run {run}; got {len(files)}")

    raw = read_raw_edf(files[0], preload=True, verbose=False)
    eegbci.standardize(raw)
    raw.resample(CFG.target_sfreq, npad="auto", verbose=False)
    raw.pick(picks="eeg")
    raw.set_montage("standard_1005", on_missing="raise", verbose=False)
    raw.set_eeg_reference("average", projection=False, verbose=False)
    raw.filter(
        CFG.l_freq,
        CFG.h_freq,
        picks="eeg",
        method="fir",
        phase="zero",
        fir_design="firwin",
        skip_by_annotation="edge",
        verbose=False,
    )

    missing = sorted(set(SENSORIMOTOR_CHANNELS) - set(raw.ch_names))
    if missing:
        raise RuntimeError(f"Missing required channels: {missing}")
    raw.pick(SENSORIMOTOR_CHANNELS)

    events, _ = mne.events_from_annotations(
        raw,
        event_id={"T1": 1, "T2": 2},
        verbose=False,
    )
    if not len(events):
        raise RuntimeError("No T1/T2 annotations found")

    event_names = np.where(events[:, 2] == 1, "T1", "T2")
    metadata = pd.DataFrame({
        "subject": subject,
        "run": run,
        "condition": condition,
        "label": int(condition == "execution"),
        "task_family": task_family,
        "repetition": repetition,
        "event_name": event_names,
        "movement": [movement_name(task_family, e) for e in event_names],
        "onset_seconds": events[:, 0] / raw.info["sfreq"],
        "source_file": Path(files[0]).name,
    })

    epochs = mne.Epochs(
        raw,
        events,
        event_id={"T1": 1, "T2": 2},
        tmin=CFG.epoch_tmin,
        tmax=CFG.epoch_tmax,
        baseline=None,
        preload=True,
        reject={"eeg": CFG.reject_peak_to_peak_uv * 1e-6},
        reject_by_annotation=True,
        metadata=metadata,
        event_repeated="drop",
        verbose=False,
    )
    epochs.load_data()

    log_row = {
        "subject": subject,
        "run": run,
        "condition": condition,
        "task_family": task_family,
        "n_events": len(events),
        "n_kept": len(epochs),
        "n_rejected": len(events) - len(epochs),
        "rejection_rate": 1.0 - (len(epochs) / len(events)),
        "status": "ok" if len(epochs) else "all_rejected",
        "error": "",
    }
    return epochs, log_row


def build_epoch_dataset(subjects):
    retained_subject_epochs = []
    log_rows = []
    required_runs = set(CFG.task_runs)

    for subject in subjects:
        print(f"Subject {subject:03d}/{max(subjects):03d}", end="\r")
        subject_epochs = []
        kept_runs = set()

        for run in CFG.task_runs:
            try:
                run_epochs, row = load_run(subject, run)
                log_rows.append(row)

                if len(run_epochs):
                    subject_epochs.append(run_epochs)
                    kept_runs.add(run)

            except Exception as exc:
                condition, task_family, _ = RUN_INFO[run]
                log_rows.append({
                    "subject": subject,
                    "run": run,
                    "condition": condition,
                    "task_family": task_family,
                    "n_events": np.nan,
                    "n_kept": 0,
                    "n_rejected": np.nan,
                    "rejection_rate": np.nan,
                    "status": "error",
                    "error": repr(exc),
                })

        # Retain only participants satisfying the existing complete-case rule
        if required_runs.issubset(kept_runs):
            subject_combined = mne.concatenate_epochs(
                subject_epochs,
                add_offset=True,
                on_mismatch="raise",
                verbose=False,
            )
            retained_subject_epochs.append(subject_combined)

        del subject_epochs
        gc.collect()

    loading_log = pd.DataFrame(log_rows)

    if len(retained_subject_epochs) < CFG.outer_folds:
        raise RuntimeError(
            f"Only {len(retained_subject_epochs)} complete participants; "
            f"need at least {CFG.outer_folds}."
        )

    combined = mne.concatenate_epochs(
        retained_subject_epochs,
        add_offset=True,
        on_mismatch="raise",
        verbose=False,
    )
    combined.metadata = combined.metadata.reset_index(drop=True)

    del retained_subject_epochs
    gc.collect()

    return combined, loading_log

# This is the slowest data-acquisition step. A full first run downloads and
# preprocesses all requested EEGMMIDB task files; subsequent runs use the cache.
if EPOCH_CACHE.exists() and LOAD_LOG_CACHE.exists():
    epochs = mne.read_epochs(EPOCH_CACHE, preload=True, verbose=False)
    loading_log = pd.read_csv(LOAD_LOG_CACHE)
    print("Loaded cached epochs and quality-control log.")
else:
    epochs, loading_log = build_epoch_dataset(CFG.subjects)
    epochs.save(EPOCH_CACHE, overwrite=True, verbose=False)
    loading_log.to_csv(LOAD_LOG_CACHE, index=False)
    print("Saved epoch and quality-control caches.")

metadata = epochs.metadata.copy().reset_index(drop=True)
print(f"Retained participants: {metadata.subject.nunique()}")
print(f"Retained epochs: {len(metadata)}")
display(pd.crosstab(metadata["condition"], metadata["task_family"], margins=True))

# Quality-control tables that must be reported or archived with the paper.
failed_runs = loading_log[loading_log["status"] != "ok"].copy()
requested = set(CFG.subjects)
retained = set(map(int, metadata.subject.unique()))
excluded = sorted(requested - retained)

print("Excluded participant IDs:", excluded)
print("Failed/all-rejected runs:", len(failed_runs))
if len(failed_runs):
    display(failed_runs)

rejection_summary = (
    loading_log[loading_log["status"].isin(["ok", "all_rejected"])]
    .groupby("condition", as_index=False)
    .agg(
        events=("n_events", "sum"),
        kept=("n_kept", "sum"),
        mean_run_rejection=("rejection_rate", "mean"),
    )
)
rejection_summary["pooled_rejection"] = 1 - rejection_summary["kept"] / rejection_summary["events"]
display(rejection_summary)

subject_counts = pd.crosstab(metadata.subject, metadata.condition)
display(subject_counts.describe())

loading_log.to_csv(OUTPUT_DIR / "loading_and_rejection_qc.csv", index=False)
rejection_summary.to_csv(OUTPUT_DIR / "rejection_summary_by_condition.csv", index=False)
pd.DataFrame({"excluded_subject": excluded}).to_csv(
    OUTPUT_DIR / "excluded_participants.csv", index=False
)

"""## Interpretable ERD features

For each retained channel, Welch power is calculated in the mu (8–13 Hz) and beta (13–30 Hz) bands. The feature is a baseline-referenced decibel ratio:

$$\mathrm{ERD/ERS}_{c,b}=10\log_{10}\left(\frac{P_{c,b}^{\mathrm{task}}+\epsilon}{P_{c,b}^{\mathrm{baseline}}+\epsilon}\right).$$

Negative values indicate task-period power reduction relative to the pre-cue rest interval; positive values indicate an increase. This produces 42 interpretable features (21 channels × 2 bands) and avoids the very high-dimensional flattened Mel representation. Feature extraction itself is label-free; the supervised selector remains inside cross-validation.

"""

BANDS = {"mu": (8.0, 13.0), "beta": (13.0, 30.0)}


def band_powers(data, sfreq, bands=BANDS):
    n_times = data.shape[-1]
    n_fft = min(256, n_times)
    psd, freqs = psd_array_welch(
        data,
        sfreq=sfreq,
        fmin=min(v[0] for v in bands.values()),
        fmax=max(v[1] for v in bands.values()),
        n_fft=n_fft,
        n_per_seg=n_fft,
        n_overlap=n_fft // 2,
        average="mean",
        verbose=False,
    )
    output = {}
    for name, (low, high) in bands.items():
        # Avoid double-counting 13 Hz in the two adjacent bands.
        mask = (freqs >= low) & (freqs < high if high < 30 else freqs <= high)
        output[name] = scipy.integrate.trapezoid(psd[..., mask], freqs[mask], axis=-1)
    return output


def extract_erd_features(epochs):
    baseline = epochs.copy().crop(CFG.baseline_tmin, CFG.baseline_tmax)
    task = epochs.copy().crop(CFG.task_tmin, CFG.task_tmax)
    baseline_power = band_powers(baseline.get_data(copy=False), epochs.info["sfreq"])
    task_power = band_powers(task.get_data(copy=False), epochs.info["sfreq"])

    feature_blocks = []
    feature_names = []
    eps = np.finfo(float).tiny
    for band in BANDS:
        feature_blocks.append(10 * np.log10((task_power[band] + eps) / (baseline_power[band] + eps)))
        feature_names.extend([f"{channel}_{band}_erd_db" for channel in epochs.ch_names])

    X = np.concatenate(feature_blocks, axis=1)
    if not np.isfinite(X).all():
        raise ValueError("Non-finite ERD features found; inspect PSD and epoch quality.")
    return X, feature_names


X_erd, erd_feature_names = extract_erd_features(epochs)
y = metadata["label"].to_numpy(dtype=int)
groups = metadata["subject"].to_numpy(dtype=int)
X_csp = epochs.copy().crop(CFG.task_tmin, CFG.task_tmax).get_data(copy=True).astype(np.float64)

assert X_erd.shape == (len(metadata), len(erd_feature_names))
assert X_csp.shape[0] == len(metadata) == len(y) == len(groups)
assert set(np.unique(y)) == {0, 1}
print("ERD feature matrix:", X_erd.shape)
print("CSP input tensor:", X_csp.shape)

"""## Nested participant-disjoint evaluation

The same participant folds are reused across models and duration analyses. The outer folds estimate performance on unseen participants. Each outer training set contains a second participant-disjoint cross-validation loop for hyperparameter selection. The held-out outer participants are not used to choose features, CSP filters, regularization, or hyperparameters.

Participant-level means and confidence intervals are primary because the scientific population consists of participants, not independent EEG segments. Epoch-pooled values are retained as secondary descriptive results.

"""

METRIC_NAMES = [
    "balanced_accuracy", "roc_auc", "macro_f1", "sensitivity",
    "specificity", "average_precision", "accuracy", "mcc",
]


def make_group_folds(groups, n_splits, seed):
    unique_groups = np.array(sorted(np.unique(groups)))
    if len(unique_groups) < n_splits:
        raise ValueError(f"Need at least {n_splits} groups; got {len(unique_groups)}")
    splitter = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
    folds = []
    for train_g_idx, test_g_idx in splitter.split(unique_groups):
        train_groups = unique_groups[train_g_idx]
        test_groups = unique_groups[test_g_idx]
        train_idx = np.flatnonzero(np.isin(groups, train_groups))
        test_idx = np.flatnonzero(np.isin(groups, test_groups))
        assert set(groups[train_idx]).isdisjoint(set(groups[test_idx]))
        folds.append((train_idx, test_idx))
    return folds


def continuous_score(estimator, X):
    if hasattr(estimator, "predict_proba"):
        return estimator.predict_proba(X)[:, 1]
    if hasattr(estimator, "decision_function"):
        raw = np.asarray(estimator.decision_function(X), dtype=float)
        return 1.0 / (1.0 + np.exp(-np.clip(raw, -40, 40)))
    raise TypeError("Estimator must expose predict_proba or decision_function for ROC–AUC.")


def compute_metrics(y_true, y_pred, y_score):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return {
        "balanced_accuracy": balanced_accuracy_score(y_true, y_pred),
        "roc_auc": roc_auc_score(y_true, y_score),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "sensitivity": tp / (tp + fn) if (tp + fn) else np.nan,
        "specificity": tn / (tn + fp) if (tn + fp) else np.nan,
        "average_precision": average_precision_score(y_true, y_score),
        "accuracy": accuracy_score(y_true, y_pred),
        "mcc": matthews_corrcoef(y_true, y_pred),
    }


def participant_metric_table(oof):
    rows = []
    for subject, frame in oof.groupby("subject", sort=True):
        if frame["y_true"].nunique() != 2:
            continue
        rows.append({"subject": int(subject), **compute_metrics(
            frame["y_true"].to_numpy(),
            frame["y_pred"].to_numpy(),
            frame["y_score"].to_numpy(),
        )})
    return pd.DataFrame(rows)


def bootstrap_participant_means(subject_metrics, n_bootstrap, seed):
    rng = np.random.default_rng(seed)
    values = subject_metrics[METRIC_NAMES].to_numpy(dtype=float)
    boot = np.empty((n_bootstrap, values.shape[1]), dtype=float)
    for i in range(n_bootstrap):
        sample = rng.integers(0, len(values), size=len(values))
        boot[i] = np.nanmean(values[sample], axis=0)
    rows = []
    for j, metric in enumerate(METRIC_NAMES):
        rows.append({
            "metric": metric,
            "participant_mean": np.nanmean(values[:, j]),
            "ci_low": np.nanquantile(boot[:, j], 0.025),
            "ci_high": np.nanquantile(boot[:, j], 0.975),
        })
    return pd.DataFrame(rows)


def selected_feature_rows(best_estimator, feature_names, fold):
    if feature_names is None or not hasattr(best_estimator, "named_steps"):
        return []
    selector = best_estimator.named_steps.get("select")
    classifier = best_estimator.named_steps.get("classifier")
    if selector is None or classifier is None or not hasattr(selector, "get_support"):
        return []
    support = selector.get_support()
    coefs = np.ravel(classifier.coef_)
    return [
        {
            "fold": fold,
            "feature": feature,
            "coefficient": float(coef),
        }
        for feature, coef in zip(np.asarray(feature_names)[support], coefs)
    ]


def run_nested_group_cv(
    model_name,
    X,
    y,
    groups,
    metadata,
    estimator,
    param_grid,
    feature_names=None,
    verbose=True,
):
    outer_folds = make_group_folds(groups, CFG.outer_folds, CFG.seed)
    oof_rows, fold_rows, feature_rows = [], [], []

    for fold, (train_idx, test_idx) in enumerate(outer_folds, start=1):
        inner_cv = make_group_folds(
            groups[train_idx],
            min(CFG.inner_folds, len(np.unique(groups[train_idx]))),
            CFG.seed + fold,
        )
        search = GridSearchCV(
            estimator=clone(estimator),
            param_grid=param_grid,
            scoring="roc_auc",
            cv=inner_cv,
            refit=True,
            n_jobs=CFG.n_jobs,
            return_train_score=False,
            error_score="raise",
        )
        search.fit(X[train_idx], y[train_idx])
        best = search.best_estimator_
        y_score = continuous_score(best, X[test_idx])
        y_pred = best.predict(X[test_idx]).astype(int)
        fold_metric = compute_metrics(y[test_idx], y_pred, y_score)
        fold_rows.append({
            "model": model_name,
            "fold": fold,
            "n_train_subjects": len(np.unique(groups[train_idx])),
            "n_test_subjects": len(np.unique(groups[test_idx])),
            "n_train_epochs": len(train_idx),
            "n_test_epochs": len(test_idx),
            "best_inner_auc": search.best_score_,
            "best_params": json.dumps(search.best_params_, sort_keys=True),
            **fold_metric,
        })
        feature_rows.extend(selected_feature_rows(best, feature_names, fold))

        for local_i, global_i in enumerate(test_idx):
            row = metadata.iloc[global_i]
            oof_rows.append({
                "model": model_name,
                "epoch_index": int(global_i),
                "fold": fold,
                "subject": int(groups[global_i]),
                "run": int(row["run"]),
                "condition": row["condition"],
                "task_family": row["task_family"],
                "movement": row["movement"],
                "onset_seconds": float(row["onset_seconds"]),
                "y_true": int(y[global_i]),
                "y_pred": int(y_pred[local_i]),
                "y_score": float(y_score[local_i]),
            })
        if verbose:
            print(
                f"{model_name} fold {fold}/{CFG.outer_folds}: "
                f"balanced accuracy={fold_metric['balanced_accuracy']:.3f}, "
                f"AUC={fold_metric['roc_auc']:.3f}"
            )

    oof = pd.DataFrame(oof_rows).sort_values("epoch_index").reset_index(drop=True)
    folds = pd.DataFrame(fold_rows)
    subject_metrics = participant_metric_table(oof)
    summary = bootstrap_participant_means(subject_metrics, CFG.n_bootstrap, CFG.seed)
    summary.insert(0, "model", model_name)
    features = pd.DataFrame(feature_rows)
    return {
        "model": model_name,
        "oof": oof,
        "folds": folds,
        "subject_metrics": subject_metrics,
        "summary": summary,
        "selected_features": features,
    }

erd_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median", add_indicator=False)),
    ("scaler", StandardScaler()),
    ("select", SelectKBest(score_func=f_classif)),
    ("classifier", LogisticRegression(
        solver="liblinear",
        class_weight="balanced",
        max_iter=5000,
        random_state=CFG.seed,
    )),
])
erd_grid = {
    "select__k": [10, 20, 30, "all"],
    "classifier__C": [0.01, 0.1, 1.0, 10.0],
}

csp_model = Pipeline([
    ("csp", CSP(
        n_components=6,
        reg="ledoit_wolf",
        log=True,
        norm_trace=False,
        cov_est="concat",
        transform_into="average_power",
    )),
    ("classifier", LinearDiscriminantAnalysis(solver="lsqr", shrinkage="auto")),
])
csp_grid = {
    "csp__n_components": [4, 6, 8, 10],
    "csp__reg": [None, "ledoit_wolf"],
}

riemann_model = Pipeline([
    ("covariance", Covariances(estimator="lwf")),
    ("tangent", TangentSpace(metric="riemann")),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        solver="liblinear",
        class_weight="balanced",
        max_iter=5000,
        random_state=CFG.seed,
    )),
])
riemann_grid = {
    "classifier__C": [0.01, 0.1, 1.0, 10.0],
}

dummy_model = DummyClassifier(strategy="prior", random_state=CFG.seed)

results = {}
results["dummy"] = run_nested_group_cv(
    "Dummy prior", X_erd, y, groups, metadata,
    dummy_model, param_grid={}, verbose=False,
)
results["erd"] = run_nested_group_cv(
    "ERD logistic regression", X_erd, y, groups, metadata,
    erd_model, erd_grid, feature_names=erd_feature_names,
)
if CFG.run_csp:
    results["csp"] = run_nested_group_cv(
        "CSP–LDA", X_csp, y, groups, metadata,
        csp_model, csp_grid,
    )
if CFG.run_riemann:
    results["riemann"] = run_nested_group_cv(
        "Riemannian tangent-space LR", X_csp, y, groups, metadata,
        riemann_model, riemann_grid,
    )

summary = pd.concat([r["summary"] for r in results.values()], ignore_index=True)
display(summary[summary.metric.isin(["balanced_accuracy", "roc_auc", "macro_f1"])]
        .round(3))

# Fold-level and participant-level visual summaries.
fold_results = pd.concat([r["folds"] for r in results.values()], ignore_index=True)
participant_results = pd.concat(
    [r["subject_metrics"].assign(model=r["model"]) for r in results.values()],
    ignore_index=True,
)

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5), constrained_layout=True)
palette = ["#777777", "#2C6E9B", "#D07A2D", "#5D8A61"][: participant_results.model.nunique()]
for ax, metric, label in zip(
    axes,
    ["balanced_accuracy", "roc_auc"],
    ["Participant-level balanced accuracy", "Participant-level ROC–AUC"],
):
    sns.boxplot(data=participant_results, x="model", y=metric, ax=ax, palette=palette)
    sns.stripplot(
        data=participant_results, x="model", y=metric,
        ax=ax, color="black", alpha=0.28, size=2.5, jitter=0.25,
    )
    ax.axhline(0.5, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("")
    ax.set_ylabel(label)
    ax.tick_params(axis="x", rotation=18)
plt.show()

display(fold_results.round(3))

# Training-fold feature stability for the interpretable ERD model.
selected = results["erd"]["selected_features"]
if len(selected):
    stability = (
        selected.groupby("feature", as_index=False)
        .agg(
            selected_folds=("fold", "nunique"),
            median_coefficient=("coefficient", "median"),
            mean_abs_coefficient=("coefficient", lambda x: np.mean(np.abs(x))),
        )
        .sort_values(["selected_folds", "mean_abs_coefficient"], ascending=False)
    )
    display(stability.head(20))

    top = stability.head(15).sort_values("mean_abs_coefficient")
    colors = np.where(top.median_coefficient >= 0, "#B75D38", "#2C6E9B")
    plt.figure(figsize=(8, 5.5))
    plt.barh(top.feature, top.mean_abs_coefficient, color=colors)
    plt.xlabel("Mean absolute logistic coefficient across selecting folds")
    plt.ylabel("")
    plt.title("Stable fold-local ERD features")
    plt.tight_layout()
    plt.show()

    stability.to_csv(OUTPUT_DIR / "erd_feature_stability.csv", index=False)

# Prespecified subgroup description. These are secondary, not independent tests.
primary_oof = results["erd"]["oof"]
subgroup_rows = []
for (family, movement), frame in primary_oof.groupby(["task_family", "movement"]):
    if frame.y_true.nunique() == 2:
        subgroup_rows.append({
            "task_family": family,
            "movement": movement,
            "n_epochs": len(frame),
            "n_subjects": frame.subject.nunique(),
            **compute_metrics(frame.y_true, frame.y_pred, frame.y_score),
        })
subgroup_results = pd.DataFrame(subgroup_rows)
display(subgroup_results.round(3))
subgroup_results.to_csv(OUTPUT_DIR / "subgroup_metrics_erd_model.csv", index=False)

"""## Duration sensitivity analysis

The original workflow compared a flattened representation of the first 60 seconds with one of the full run. Here the scientific unit remains an event-related trial. The sensitivity analysis asks whether training and evaluating on cue events occurring in the first 60 seconds changes unseen-participant performance relative to using all cue events. It uses the same ERD pipeline and the same deterministic participant-fold assignment.

A paired participant-level difference and its bootstrap interval are more informative than comparing the single best classifier from two unrelated random splits.

"""

def paired_bootstrap_difference(frame_a, frame_b, metric, n_bootstrap, seed):
    paired = frame_a[["subject", metric]].merge(
        frame_b[["subject", metric]], on="subject", suffixes=("_a", "_b")
    ).dropna()
    diff = paired[f"{metric}_b"] - paired[f"{metric}_a"]
    rng = np.random.default_rng(seed)
    boot = np.empty(n_bootstrap)
    for i in range(n_bootstrap):
        boot[i] = rng.choice(diff.to_numpy(), size=len(diff), replace=True).mean()
    return {
        "metric": metric,
        "mean_full_minus_first60": diff.mean(),
        "ci_low": np.quantile(boot, 0.025),
        "ci_high": np.quantile(boot, 0.975),
        "wilcoxon_p": wilcoxon(diff).pvalue if np.any(diff != 0) else 1.0,
        "n_subjects": len(diff),
    }


duration_results = {}
if CFG.run_duration_sensitivity:
    mask_60 = metadata["onset_seconds"].to_numpy() < 60.0
    duration_results["first60"] = run_nested_group_cv(
        "ERD first-60-s events", X_erd[mask_60], y[mask_60], groups[mask_60],
        metadata.loc[mask_60].reset_index(drop=True), erd_model, erd_grid,
        feature_names=erd_feature_names,
    )
    duration_results["full"] = results["erd"]

    duration_comparison = pd.DataFrame([
        paired_bootstrap_difference(
            duration_results["first60"]["subject_metrics"],
            duration_results["full"]["subject_metrics"],
            metric,
            CFG.n_bootstrap,
            CFG.seed,
        )
        for metric in ["balanced_accuracy", "roc_auc", "macro_f1"]
    ])
    display(duration_comparison.round(4))
    duration_comparison.to_csv(OUTPUT_DIR / "duration_paired_comparison.csv", index=False)

"""## Optional group-aware permutation test

This test randomly swaps the ME/MI assignment within each participant, preserving participant structure and class balance. It reruns the complete nested selection procedure for every permutation, so it is intentionally disabled by default and computationally expensive. Enable it for the final paper run. A small number such as 20 is useful only to test the code; use the prespecified 1,000 permutations for inference.

"""

def flip_labels_by_subject(y, groups, rng):
    y_perm = y.copy()
    for subject in np.unique(groups):
        idx = groups == subject
        if rng.random() < 0.5:
            y_perm[idx] = 1 - y_perm[idx]
    return y_perm


def nested_group_permutation_test(X, y, groups, metadata, estimator, param_grid, n_permutations):
    observed_result = results["erd"]
    observed = observed_result["subject_metrics"]["balanced_accuracy"].mean()
    rng = np.random.default_rng(CFG.seed)
    null = np.empty(n_permutations)

    for permutation in range(n_permutations):
        y_perm = flip_labels_by_subject(y, groups, rng)
        permuted = run_nested_group_cv(
            f"permutation_{permutation + 1}",
            X, y_perm, groups, metadata, estimator, param_grid,
            verbose=False,
        )
        null[permutation] = permuted["subject_metrics"]["balanced_accuracy"].mean()
        print(f"Permutation {permutation + 1}/{n_permutations}", end="\r")

    p_value = (1 + np.sum(null >= observed)) / (n_permutations + 1)
    return observed, null, p_value


if CFG.run_permutation_test:
    observed_bacc, null_bacc, permutation_p = nested_group_permutation_test(
        X_erd, y, groups, metadata, erd_model, erd_grid, CFG.n_permutations
    )
    print({"observed_participant_mean_balanced_accuracy": observed_bacc,
           "permutation_p": permutation_p})
    np.save(OUTPUT_DIR / "balanced_accuracy_permutation_null.npy", null_bacc)
    pd.DataFrame([{
        "observed_participant_mean_balanced_accuracy": observed_bacc,
        "n_permutations": CFG.n_permutations,
        "p_value": permutation_p,
    }]).to_csv(OUTPUT_DIR / "permutation_test.csv", index=False)
else:
    print("Permutation test not run. Set run_permutation_test=True in AnalysisConfig for final inference.")

"""## Export manuscript-ready results

The export includes out-of-fold predictions, fold metrics, participant metrics, bootstrap summaries, quality-control tables, model settings, exclusions, and software versions. These are the files from which the paper's tables and figures should be generated. Avoid manually transcribing results from notebook display cells.

"""

software_versions = {
    "python": platform.python_version(),
    "mne": mne.__version__,
    "numpy": np.__version__,
    "pandas": pd.__version__,
    "scipy": scipy.__version__,
    "scikit_learn": sklearn.__version__,
    "pyriemann": pyriemann.__version__,
}
(OUTPUT_DIR / "software_versions.json").write_text(json.dumps(software_versions, indent=2))

summary.to_csv(OUTPUT_DIR / "participant_bootstrap_summary.csv", index=False)
fold_results.to_csv(OUTPUT_DIR / "outer_fold_metrics.csv", index=False)
participant_results.to_csv(OUTPUT_DIR / "participant_metrics.csv", index=False)
for key, result in results.items():
    result["oof"].to_csv(OUTPUT_DIR / f"oof_predictions_{key}.csv", index=False)

archive = shutil.make_archive(str(WORK_DIR / "EEG_ME_MI_paper_outputs"), "zip", OUTPUT_DIR)
print(f"Exported reproducibility package: {archive}")
print("Inspect every CSV before using the results in the manuscript.")

import numpy as np
import pandas as pd

sampling_check = pd.DataFrame([{
    "configured_target_hz": float(CFG.target_sfreq),
    "actual_epoch_data_hz": float(epochs.info["sfreq"]),
    "number_of_epochs": len(epochs),
    "samples_per_epoch": len(epochs.times),
    "epoch_start_s": float(epochs.tmin),
    "epoch_end_s": float(epochs.tmax),
}])

display(sampling_check)

assert np.isclose(
    epochs.info["sfreq"], 80.0
), f"The analysed epochs used {epochs.info['sfreq']} Hz, not 80 Hz."

sampling_check.to_csv(
    OUTPUT_DIR / "sampling_rate_verification.csv",
    index=False
)

"""## How to revise the paper after the full run

1. **Change the unit of analysis.** State the exact number of retained participants and T1/T2 epochs after rejection, with excluded IDs and reasons.
2. **Describe the run mapping explicitly.** Execution and imagery are assigned by run number; T1/T2 identify movement cues within a run.
3. **Replace the recording-level Mel method as the primary analysis.** Present baseline-referenced mu/beta ERD logistic regression as the interpretable primary model and CSP–LDA as the EEG-specific comparator. The original Mel result can remain as an exploratory or supplementary analysis only if it is rerun leakage-safely.
4. **Report generalization correctly.** Say “performance for unseen participants under nested participant-disjoint cross-validation,” and give participant-mean metrics with 95% intervals, outer-fold results, and the permutation p-value.
5. **Interpret modest performance honestly.** If the confidence interval includes 0.50 or the permutation test is not significant, conclude that the analysis did not demonstrate reliable cross-participant ME–MI decoding.
6. **Separate neural interpretation from artifact sensitivity.** Discuss the absence of dedicated EOG/EMG channels and the differential-rejection check.
7. **Rename the duration comparison.** Use “first-60-second events versus all events,” not “60-second versus 120-second epochs.”
8. **Remove deployment claims unless separately tested.** An offline public-dataset benchmark does not establish online BCI readiness, clinical benefit, or real-time latency.

A strong paper is possible, but its contribution is more credible as a transparent cross-participant benchmark and methodological comparison than as a high-accuracy or deployment-ready system.

## Literature to integrate

The following sources support the protocol, physiological framing, EEG-specific baselines, and leakage-safe evaluation. They were selected for direct relevance; papers that classify left/right or upper/lower movement should not be compared numerically as if they solve the same ME-versus-MI problem.

- Schalk G. **EEG Motor Movement/Imagery Dataset**, PhysioNet v1.0.0 (2009). https://doi.org/10.13026/C28G6P
- Schalk G, McFarland DJ, Hinterberger T, Birbaumer N, Wolpaw JR. **BCI2000: a general-purpose brain-computer interface system.** *IEEE Transactions on Biomedical Engineering* (2004). https://doi.org/10.1109/TBME.2004.827072
- Pfurtscheller G, Lopes da Silva FH. **Event-related EEG/MEG synchronization and desynchronization: basic principles.** *Clinical Neurophysiology* (1999). https://doi.org/10.1016/S1388-2457(99)00141-8
- Pfurtscheller G, Neuper C. **Motor imagery activates primary sensorimotor area in humans.** *Neuroscience Letters* (1997). https://doi.org/10.1016/S0304-3940(97)00889-6
- Ang KK et al. **Filter Bank Common Spatial Pattern Algorithm on BCI Competition IV datasets 2a and 2b.** *Frontiers in Neuroscience* (2012). https://doi.org/10.3389/fnins.2012.00039
- Barachant A et al. **Multiclass brain–computer interface classification by Riemannian geometry.** *IEEE Transactions on Biomedical Engineering* (2012). https://doi.org/10.1109/TBME.2011.2172210
- Lotte F et al. **A review of classification algorithms for EEG-based BCIs: a 10 year update.** *Journal of Neural Engineering* (2018). https://doi.org/10.1088/1741-2552/aab2f2
- Lawhern VJ et al. **EEGNet: a compact convolutional neural network for EEG-based BCIs.** *Journal of Neural Engineering* (2018). https://doi.org/10.1088/1741-2552/aace8c
- Shuqfa Z, Belkacem AN, Lakas A. **Decoding multi-class motor imagery and motor execution tasks using Riemannian geometry algorithms on large EEG datasets.** *Sensors* (2023). https://doi.org/10.3390/s23115051
- Mwata-Velu T et al. **EEG-BCI features discrimination between executed and imagined movements based on FastICA, Hjorth parameters, and SVM.** *Mathematics* (2023). https://doi.org/10.3390/math11214409
- Brookshire G et al. **Data leakage in deep learning studies of translational EEG.** *Frontiers in Neuroscience* (2024). https://doi.org/10.3389/fnins.2024.1373515
- Rosenblatt M et al. **Data leakage inflates prediction performance in connectome-based machine learning models.** *Nature Communications* (2024). https://doi.org/10.1038/s41467-024-46150-w
- Shim M, Lee SH, Hwang HJ. **Inflated prediction accuracy of neuropsychiatric biomarkers caused by data leakage in feature selection.** *Scientific Reports* (2021). https://doi.org/10.1038/s41598-021-87157-3
- Combrisson E, Jerbi K. **Exceeding chance level by chance.** *Journal of Neuroscience Methods* (2015). https://doi.org/10.1016/j.jneumeth.2015.01.010
- Varoquaux G. **Cross-validation failure: small sample sizes lead to large error bars.** *NeuroImage* (2018). https://doi.org/10.1016/j.neuroimage.2017.06.061
- Adeyemi A, Adesokan O, Adediran D, Ige O. **Machine Learning in Healthcare.** IMEETMCON (2018). Use this once in the introduction to connect the work to the broader clinical-machine-learning context; it should not be used as evidence for an EEG-specific preprocessing decision.

## Final submission checklist

- [ ] All 109 requested participants were attempted and exclusions are listed with objective reasons.
- [ ] The class and task-family counts are balanced or any imbalance is explained.
- [ ] Differential ME/MI rejection is reported and sensitivity analyses are archived.
- [ ] No participant occurs in both train and test partitions in any fold.
- [ ] Feature selection, scaling, CSP, and tuning occur only inside training folds.
- [ ] ROC–AUC uses probabilities/scores, not hard predictions.
- [ ] Participant-mean results, 95% bootstrap intervals, outer-fold results, and permutation inference are reported.
- [ ] The code, configuration, exclusions, predictions, and software versions are deposited in a permanent repository.
- [ ] Numerical comparisons in Related Work are restricted to studies with a genuinely comparable task and validation design.
- [ ] Claims distinguish offline decoding, cross-participant generalization, neurophysiological interpretation, and clinical/online deployment.
"""